package com.exe.loginyregister.Enum;

public enum TipoDocumento {
    DOCUMENTO_CONVENIO,
    CARTA_ACEPTACION,
    DOCUMENTO_DOBLE_TITULACION,
    AVAL_CONSEJO,
    CARTA_PRESENTACION,
    RECIBO_MATRICULA,
    SEGURO_MEDICO,
    FORMATO_LLEGADA,
    CONTRATO_ESTUDIOS,
    SOLICITUD_CONVALIDACION,
    DOCUMENTO_SOPORTE;
}
